name: Staybroke poller

on:
  schedule:
    - cron: "*/5 * * * *" # every 10 minutes
  workflow_dispatch:

jobs:
  poll-job:
    runs-on: ubuntu-latest
    environment: cron 
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      FETCH_URL : ${{secrets.FETCH_URL}}
      API_KEY : ${{secrets.API_KEY}}
      WEBHOOK : ${{secrets.WEBHOOK}}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run polling script
        run: node poller.js
